version: "3"

services:
  leopays_node:
    build:
      context: .
      dockerfile: ./from-binaries.dockerfile
      args:
        - binaries_link=https://github.com/leopays-chain/leopays/releases/download/v0.1.0-rc1/leopays_0.1.0-rc1-ubuntu-18.04_amd64.deb
    image: leopays/leopays:local
    command: leopays-node.sh --data-dir /data -e --http-alias=leopays_node:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: leopays_node
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - leopays_node-data-volume:/data
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  leopays_wallet:
    build:
      context: .
      dockerfile: ./from-binaries.dockerfile
      args:
        - binaries_link=https://github.com/leopays-chain/leopays/releases/download/v0.1.0-rc1/leopays_0.1.0-rc1-ubuntu-18.04_amd64.deb
    image: leopays/leopays:local
    command: leopays-wallet --wallet-dir /data --http-server-address=127.0.0.1:8900 --http-alias=leopays_wallet:8900 --http-alias=localhost:8900
    hostname: leopays_wallet
    links:
      - leopays_node
    volumes:
      - leopays_wallet-data-volume:/data
    stop_grace_period: 10m

volumes:
 leopays_node-data-volume:
   external: true
 leopays_wallet-data-volume:
   external: true
